server:
  servlet:
    context-path: /  # 루트 경로 유지
spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ksi4788500!
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 2
      leak-detection-threshold: 30000
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    com.psim: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG