spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ksi4788500!}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 120000

logging:
  level:
    com.psim: INFO
    com.zaxxer.hikari: WARN
    org.springframework.jdbc: WARN
    org.springframework.transaction: INFO
    root: WARN